services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=OakTree2025
    #   - POSTGRES_DB=bond_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # reservations:
  #   build:
  #     context: .
  #     dockerfile: ./apps/reservations/Dockerfile
  #     target: development
  #   command: pnpm run start:dev reservations
  #   env_file:
  #     - ./apps/reservations/.env
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  bonds:
    build:
      context: .
      dockerfile: ./apps/bonds/Dockerfile
      target: development
    command: pnpm run start:dev bonds
    env_file:
      - ./apps/bonds/.env
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
  # notifications:
  #   build:
  #     context: .
  #     dockerfile: ./apps/notifications/Dockerfile
  #     target: development
  #   command: pnpm run start:dev notifications
  #   env_file:
  #     - ./apps/notifications/.env
  #   volumes:
  #     - .:/usr/src/app
  mongo:
    image: mongo

  
volumes:
  postgres-data: